version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - setup_remote_docker
      - run: echo 'export NODE_OPTIONS=--max_old_space_size=4096' >> $BASH_ENV
      - run: npm ci
      - run: npm run test -- --runInBand
      - run: npm run build
